### ISSUE TITLE
All emojis are not centered somehow?

### ISSUE THREAD

**Issue by ghost** [Natalcia/catmoji-colr#4]
![IMG_20200822_202616_408](https://user-images.githubusercontent.com/42698724/90956068-bda2d480-e4b5-11ea-93a8-fd979e4bc41a.jpg)
![IMG_20200822_202739_763](https://user-images.githubusercontent.com/42698724/90956106-f2169080-e4b5-11ea-98b9-59a8f571aa1a.jpg)

And there are lots of missing emojis

**Comment by thaqalayn** [comment]
Might be an issue with that OS, on android its centered just fine

**Comment by ghost** [comment]
> Might be an issue with that OS, on android its centered just fine

It's Telegram Android :(

**Comment by thaqalayn** [comment]
hmmmm, im p sure there was an issue with telegram that nat had to fix, i think it was on desktop tho, #3, you'd have to ask nat to help with that lol cuz i have no idea

**Comment by surfaceflinger** [comment]
Issue with crashing is only on telegram-desktop on Linux and it's something that I can't really fix because it's probably broken COLR handling in client. 

About bad alignment on Android - I don't have any problems on Gboard and software based on latest Chromium but on Nekogram it sure looks weird. I will try later to build font using noto color emoji script from Google and maybe it'll fix it.

**Comment by surfaceflinger** [comment]
Ok I think that I found a way how to build Twemoji with Google's noto scripts but please give me time because im bad

**Comment by surfaceflinger** [comment]
I uploaded Catmoji to releases (Catmoji-noto-magisk.zip) built with https://kojipkgs.fedoraproject.org//packages/twitter-twemoji-fonts/13.0.1/2.fc33/src/twitter-twemoji-fonts-13.0.1-2.fc33.src.rpm 
Noto releases are for use on Android while COLR/old version still should be used on anything else.

I'm not closing yet, if there are still any problems please reply.

Edit: I found few bugs in Noto release, will try to fix them tomorrow because my head hurts now. Weird thing is that they're only in Telegram Android app. Maybe that's why there is no system emoji option by default haha

Edit2: I'm here sweating while trying to fix few missing emojis (they're broken only in telegram) and then I for experiment I reverted to original Google NotoColorEmoji and it's broken even on original android emojis!!!!!!!!!!!!!!!!! So I'll leave them as is because I have literally no idea what to do if it's broken even in upstream
Atleast they're now centered and these that were broken in NekoInverter screenshot are now fixed

Edit3: Temp fix for these few broken emojis in Telegram is to use Nekogram instead and loading NotoColorEmoji.ttf from 13.0.1 release in Neko Settings -> Experimental -> Custom emoji font instead of having just Magisk module.
