### ISSUE TITLE
no supported glyph data table(s) present

### ISSUE THREAD

**Issue by o-t-w** [Natalcia/catmoji-colr#8]
Devtools console in latest Firefox is displaying the following error:
downloadable font: no supported glyph data table(s) present (font-family: "Catmoji" style:normal weight:400 stretch:100 src index:0) source: http://127.0.0.1:3001/Catmoji.ttf
The font seems to work ok in Chrome but not in Safari.

**Comment by surfaceflinger** [comment]
[Catmoji.ttf.zip](https://github.com/catmoji/catmoji-colr/files/7533593/Catmoji.ttf.zip)

Can you try this ttf? It's COLR variant that theoretically should work on web. I didn't include -colr in releases because I basically maintain it only for my phone and -colr is buggy on Android when installed system-wide

**Comment by o-t-w** [comment]
That works. Thanks
